# Generated by Django 5.0.4 on 2024-04-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='subject',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
