# Generated by Django 5.0.4 on 2024-05-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='orderNo',
            field=models.PositiveIntegerField(default=16000, unique=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Dispatch'), (4, 'On the way'), (5, 'Delivered'), (6, 'Cancel'), (7, 'Return')], default=2),
        ),
    ]
