# Generated by Django 5.0.4 on 2024-05-01 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_booking_delivery_date_booking_orderno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Accepted'), (3, 'Dispatch'), (4, 'On the way'), (5, 'Delivered'), (6, 'Cancel'), (7, 'Return')], default=1),
        ),
    ]
