from django.contrib import admin
from django.urls import path,include
from .import views

urlpatterns = [
    path('',views.home,name='home'),
    path('home',views.home,name='home'),
    path('product_detail',views.product_detail,name='product_detail'),
    path('admin_login',views.admin_login,name='admin_login'),
    path('admin_data',views.admin_data,name='admin_data'),
    
    path('add_category',views.add_category,name='add_category'),
    path('category_data',views.category_data,name='category_data'),
    path('view_category',views.view_category,name='view_category'),
    path('del_category',views.del_category,name='del_category'),
    path('edit_category',views.edit_category,name='edit_category'),
    path('update_category',views.update_category,name='update_category'),
    path('add_product',views.add_product,name='add_product'),
    path('product_data',views.product_data,name='product_data'),
    path('view_product',views.view_product,name='view_product'),
    path('del_product',views.del_product,name='del_product'),
    path('edit_product',views.edit_product,name='edit_product'),
    path('update_product',views.update_product,name='update_product'),
    path('create_account',views.create_account,name='create_account'),
    path('registration',views.registration,name='registration'),
    path('user_login',views.user_login,name='user_login'),
    path('login_data',views.login_data,name='login_data'),
    path('logout_user',views.logout_user,name='logout_user'),
    path('user_profile',views.user_profile,name='user_profile'),
    path('update_profile',views.update_profile,name='update_profile'),
    path('profile_data',views.profile_data,name='profile_data'),
    path('change_password',views.change_password,name='change_password'),
    path('update_password',views.update_password,name='update_password'),
    path('feedback',views.feedback,name='feedback'),
    path('feedback_data',views.feedback_data,name='feedback_data'),
    path('add_to_cart',views.add_to_cart,name='add_to_cart'),
    path('show-cart', views.show_cart, name='show_cart'),
    path('plusCart',views.plusCart,name='plusCart'),
    path('minusCart',views.minusCart,name='minusCart'),
    path('removeCart',views.removeCart,name='removeCart'),
    path('check_out',views.check_out,name='check_out'),
    path('payment_done',views.payment_done,name='payment_done'),
    path('orders',views.orders,name='orders'),
    path('return_product',views.return_product,name='return_product'),
    path('cancel_product',views.cancel_product,name='cancel_product'),
    path('manage_feedback',views.manage_feedback,name='manage_feedback'),
    path('delete_feedback',views.delete_feedback,name='delete_feedback'),
    path('feedback-read/<int:pid>/', views.read_feedback, name="read_feedback"),
    path('manage_order',views.manage_order,name='manage_order'),
    path('delete_order/<int:id>/',views.delete_order,name='delete_order'),
    path('admin-order-track/<int:pid>/',views.admin_order_track,name='admin_order_track'),
    path('manage_user',views.manage_user,name='manage_user'),
    path('delete_user',views.delete_user,name='delete_user'),
    path('admin_change_password',views.admin_change_password,name='admin_change_password'),
    path('admin_change_password_data',views.admin_change_password_data,name='admin_change_password_data'),
    path('admin_dashboard',views.admin_dashboard,name='admin_dashboard'),
    path('admin_logout',views.admin_logout,name='admin_logout')
    
]
